### ISSUE TITLE
Crawler got stuck when running article_crawler.py

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu-ecosystem/Zeeguu-API#110]
I am running the `article_crawler.py` to test if it works with the new sources using newspaper.

When running the process for the danish sources, it got stuck in loading this article: https://www.dr.dk/stories/1288510966/det-skal-du-laegge-maerke-til-ved-aarets-oscar-nomineringer

This was on line 22 for file `zeeguu\core\content_retriever\parse_with_readability_server.py` where the request is made without a timeout parameter.

I would add a timeout of 1 minute - 2 minutes to avoid situations like this. I am not sure if this is what maybe causes the crawler to shut down?

**Comment by mircealungu** [comment]
Ah! 

I didn’t actually open the link :)
Now I see. 

So a timeout not a sleep between requests. 

For sure an article should be downloadable in 10 seconds. 30 on a slow connection. But more? More would mean that something’s wrong.

**Comment by tfnribeiro** [comment]
@mircealungu I got a notification from Sentry regarding a timeout in the crawler, so I guess this also is happening in production. 
Should we add a timeout exception to capture those cases or leave as is?

**Comment by mircealungu** [comment]
Yes, that's a good idea!
