### ISSUE TITLE
not possible to delete a cohort with students in it

### ISSUE THREAD

**Issue by mbrodt** [zeeguu-ecosystem/Zeeguu-API#57]
It should be possible to delete a cohort, even if it has students or files. I'm not exactly sure how this would work, though, since a student account is tied to a class. But it would be helpful for teachers to delete old classes they are no longer teaching.

**Comment by mircealungu** [comment]
hiding the class would be the simplest thing here.
more complicated would be deactivating the accounts for the students... 
but i would not go that far at the moment. 
maybe simply upgrade the student to individual / not-part-of-a-cohort and let them know that they are free now :)
