### ISSUE TITLE
getReadingSessions endpoint

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Zeeguu-API#61]
"getReadingSessions" object should include:

- readingSession (date), 
- title of article, 
- articleID, 
- article length, 
- article level, 
- time spent on reading the article, 
- a list of translated words in sentences with translations and isExercised boolean depending on duration.

api.getReadingSessions(studentID, cohortID, duration) - returns a list of "readingSessions" objects of what reading sessions the student has completed within the time period.

**Comment by mircealungu** [comment]
What about giving you this as the result of getReadingSessions? 

![image](https://user-images.githubusercontent.com/464519/117650167-0c55e300-b199-11eb-833e-cf225cdb21cb.png)

Then I'll give you another endpoint for `readingSessionWordDetails(reading_session_id)` that will give you the translation information?

**Comment by mircealungu** [comment]
Obviously what we see in the above is that we have both german and danish articles. 

I guess we only show the articles **in the language of the cohort**?

**Comment by majapetersen** [comment]
@mircealungu - We are missing the sentence in which a word has been translated. Hope you can provide this data as well as part of this endpoint :-)

**Comment by mircealungu** [comment]
sure. let me add it.

**Comment by mircealungu** [comment]
oki. done in https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/76b74c3070ebdc9c5b02a423f6238f00c09141b1/zeeguu_api/api/teacher_dashboard/student.py#L168. The the zeeguu.org api is also updated.

**Comment by SaraTolstrupHusum** [comment]
This is implemented in the MVP.
