### ISSUE TITLE
translation of own texts does not work in the ArticleReader

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#62]
Bypassing the url and routing straight to the ArticleReader <Link to={`/read/article?id=${articleID}`}/> from StudentTextView in the new teacher dashboard; routes to the ArticleReader without a problem, but the translations still fail.

**Comment by mircealungu** [comment]
Today I can’t replicate today the failure of the translators.
It seems to work for both german and Spanish. 

![image](https://user-images.githubusercontent.com/464519/117848721-3b00b600-b28c-11eb-98c4-92e59fc2a2ef.png)

![image](https://user-images.githubusercontent.com/464519/117848745-40f69700-b28c-11eb-81ee-e3c39cef2630.png)

Can you specify the steps to replicate the problem?

**Comment by SaraTolstrupHusum** [comment]
It is still not working in my end of the world.
I set my setting to Spanish  -> English or Danish (tried with both).
Then I go to "My Texts" - open the article (id:1524679) and click on a word to get the translation, which gives me no translation and the same internal server error in the "get_one_translation" endpoint in translations.js as earlier.

I'll try to rebase and let you know, if it works better asap.

**Comment by SaraTolstrupHusum** [comment]
![lostInTranslation](https://user-images.githubusercontent.com/64850777/117865304-1c9fb800-b296-11eb-8a11-570c361ee01e.JPG)
