### ISSUE TITLE
add delete_student_from_cohort endpoint

### ISSUE THREAD

**Issue by majapetersen** [zeeguu-ecosystem/Zeeguu-API#66]
api.deleteStudentFromCohort(studentID, cohortID)

**Comment by mircealungu** [comment]
Implemented here: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/5866e5ac4da00f7164d39b7e32ed3699d5caacbb/zeeguu_api/api/teacher_dashboard/cohorts.py#L209

**Comment by SaraTolstrupHusum** [comment]
this endpoint works like a charm.

**Comment by mircealungu** [comment]
it seems that you're expecting JSON while the endpoint returns a simple textual "OK". https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/5866e5ac4da00f7164d39b7e32ed3699d5caacbb/zeeguu_api/api/teacher_dashboard/cohorts.py#L221

**Comment by SaraTolstrupHusum** [comment]
I am console.logging it???

Implementation in teacher.js:
```
Zeeguu_API.prototype.removeStudentFromCohort = function (studentID, callback) {
  this._get(`remove_user_from_cohort/${studentID}`, callback);
};
```

How I use it in StudentInfoLine.js:
```
  const removeStudentFromCohort = () => {
    api.removeStudentFromCohort(student.id, res => console.log(res));
    setForceUpdate((prev) => prev + 1);
    setShowDeleteStudentWarning(false);
  };
```
What is it, that I am not getting? I want to learn!

**Comment by mircealungu** [comment]
@SaraTolstrupHusum 

This is what I see in my codebase:

![image](https://user-images.githubusercontent.com/464519/118613093-14c8a200-b7c7-11eb-8cc6-89800331ab2f.png)

Is it the same on your branch? 

there's both `_get` and `_getPlainText`.

We should unify the treatment of these functions, probably something like: `_getJSON` `_getPlainText`, `_postExpectingJSON` and `_postExpectingPlainText` such that it's maximally clear at the point of the call.

Alternatively we can refactor the API to always return JSON but that's an even bigger commotion.

**Comment by SaraTolstrupHusum** [comment]
Ahhh!!! Makes total sense!!! I know how to fix it now.  TNX!

**Comment by SaraTolstrupHusum** [comment]
I think it would make sense to just change the _get to _getJSON, but that might be a task all on it´s own, since all the _get. would have to be changed.

**Comment by mircealungu** [comment]
that would definitely help avoid this kind of issues in the future!

**Comment by SaraTolstrupHusum** [comment]
I fixed the bug in the code and added a new issue for better naming.
