### ISSUE TITLE
get_exercise_corectness endpoint

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Zeeguu-API#67]
1) api.getExerciseCorrectness(fromDate, studentID)​ - the overall average of the correctness of all exercises completed within the defined time by the student. 

Or correctness (student, period) = number of correct exercises (s, p) / total exercise count (s,p) YES

**Comment by mircealungu** [comment]
Implemented here: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/5866e5ac4da00f7164d39b7e32ed3699d5caacbb/zeeguu_api/api/teacher_dashboard/student.py#L82

The results will be of the form:

        e.g. GET http://localhost:9001/exercise_correctness/534/30
        {
            "Correct": 55,
            "Correct2ndTry": 55,
            "Incorrect": 4,
            "too_easy": 1,
            "Bad Example":1,
        }

See also the discussion here: 

    https://github.com/zeeguu-ecosystem/zeeguu-react/issues/38

Cf. to that discussion there are three possible states:
- correct from the 1st try
- correct from the 2nd try (use one hint)
- incorrect 

Therefore hints have to be implemented to only show one letter, or only eliminate one choice, etc. 

However, we didn't discuss what we do with the other options (too_easy, bad_example, etc.). I guess you can aggregate them under "other" and then still show them in the detail view?

Also, are you ok with absolute numbers like above and you computing the percentages in the UI? Or do you want straight percentages?

**Comment by mircealungu** [comment]
And idea that stumbled upon me after our previous discussion with @SaraTolstrupHusum @beamb and @bwesth :

If @beamb saves in the DB the sequence of steps that a user went through to arrive at an answer (hwwc = hint, wrong, wrong, correct), you @SaraTolstrupHusum and @eleonora-k  and @majapetersen can represent those steps in the UI for the teacher, with some nice and expressive unicode characters. Something like this maybe for the previous example: "!✗✗✓" (or maybe with h for hint still "h✗✗✓"). If augmented with colors, they could turn out to be effective in summarizing learner activity. 

Surely, for the summary of the activity, correct on 1st attempt could be computed in percentages, as it is now. 

P.S. This reminds me of a highly condensed form of visual representations named "sparklines" introduced by the ultimate teacher of information visualization, Edward Tufte. (https://en.wikipedia.org/wiki/Sparkline)

**Comment by SaraTolstrupHusum** [comment]
The unicode is now implemented.
