### ISSUE TITLE
getStudent(callback) or getStudent(studentID, callback) would be nice 

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#71]
Right now we are using api.loadUserInfo (endpoint:`/user_info/${userID}/${duration}`) to simply get a students name. This makes no sense, as this return a boat load of data that we don't need. It would be nice with an endpoint that simply returns the name and email of a given student based on the studentID.
The studentID will most likely be in the url everywhere where we need the student name and/or email, so it is an option to go with api.getStudent(callback), but we can easily pass the studentID as arguments if that is easier.

**Comment by SaraTolstrupHusum** [comment]
@mircealungu: We need this now. As in "must have" for finishing implementing the join cohort UI.
When a student clicks on the "Classroom" tab. He/she will see the message: "There are no articles in your classroom." even if the student has been deleted from his/her class by the teacher. We need to fix this, so that if the student is in fact not enrolled in any class, we show a "Join class"-button on the classroom page. For this we need an api call getStudent(callback) (simililar to api.getCohortArticles(callback) or api.getBookmarkedArticles(callback)) that takes no arguments but return the data pertinent to the user him/herself.
We need api.getStudent(callback) to return

- the student's name
- the student's email
- the id of the cohort the student is currently enrolled in ( if the student is not currently enrolled in any cohort - "" or null).

**Comment by mircealungu** [comment]
something like this? 

![image](https://user-images.githubusercontent.com/464519/120347201-bd691c80-c304-11eb-9bc2-0cacd3f949bc.png)

**Comment by mircealungu** [comment]
**NOTE! I've refactored it to return `cohort_id` as the last field!**

**Comment by mircealungu** [comment]
and one for the teacher side of things

![image](https://user-images.githubusercontent.com/464519/120348750-23a26f00-c306-11eb-9715-a5511cd692c2.png)

**Comment by SaraTolstrupHusum** [comment]
Precisely. Tnx!
