### ISSUE TITLE
getExercisedWords(studentID, cohortID, duration)

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#72]
Since we are now asking for three separate endpoints, we do not need the isLearned and isStudied booleans that I had implemented in the hardcoded dummies in the code. 
So this endpoint should return a list of word objects with the following properties:
```
//example word object
{
      word: "something",
      translation: "noget",
      exerciseAttempts: [
        { date: "Mar 1. 2020", type: "recognise", attempts: "wc", feedback:"" },
        { date: "Mar 2. 2020", type: "multiple choice", attempts: "c", feedback: "Too easy" },
      ],
},
```
("feedback" is the feedback the student has given on a particular exercise.)

**Comment by mircealungu** [comment]
@SaraTolstrupHusum  @eleonora-k  @majapetersen 

Can you work with something like this?

```
{
    "171945": {
        "exerciseAttempts": [
            {
                "source": "Recognize_L1W_in_L2T",
                "outcome": "C",
                "time": "2021-05-28T14:46:34",
                "exercise_id": 285493
            }
        ],
        "word": "Om dagen",
        "translation": "During the day"
    },
    "257710": {
        "exerciseAttempts": [
            {
                "source": "MULTIPLE_CHOICE",
                "outcome": "WWC",
                "time": "2021-05-28T14:46:45",
                "exercise_id": 285494
            },
            {
                "source": "MULTIPLE_CHOICE",
                "outcome": "WWC",
                "time": "2021-05-28T15:31:15",
                "exercise_id": 285498
            },
            {
                "source": "Recognize_L1W_in_L2T",
                "outcome": "too_hard",
                "time": "2021-05-28T15:33:56",
                "exercise_id": 285499
            }
        ],
        "word": "værste'",
        "translation": "worst'"
    },
    "101267": {
        "exerciseAttempts": [
            {
                "source": "Recognize_L1W_in_L2T",
                "outcome": "C",
                "time": "2021-05-28T14:46:53",
                "exercise_id": 285495
            }
        ],
        "word": "Bestemmelsessted",
        "translation": "Destination"
    },
    "157575": {
        "exerciseAttempts": [
            {
                "source": "MULTIPLE_CHOICE",
                "outcome": "C",
                "time": "2021-05-28T14:47:00",
                "exercise_id": 285496
            }
        ],
        "word": "lige ved",
        "translation": "right by"
    },
    "163836": {
        "exerciseAttempts": [
            {
                "source": "Recognize_L1W_in_L2T",
                "outcome": "C",
                "time": "2021-05-28T15:31:09",
                "exercise_id": 285497
            }
        ],
        "word": "forældre",
        "translation": "Parents"
    }
}
```

**Comment by mircealungu** [comment]
Implementation: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/0b3e4797dfcf3d709adfdd0cc1128a0f7caacdf1/zeeguu_api/api/teacher_dashboard/student_exercises.py#L64

**Comment by SaraTolstrupHusum** [comment]
I think this should work... I will try to implement it as soon as I am done with the feature, I am currently working on.

**Comment by SaraTolstrupHusum** [comment]
The api returns {} for all students. ???

**Comment by mircealungu** [comment]
Sara, can you check that it works for your own user, after you do a few exercises? 

As we've discussed currently we can only show "recent exercises" because before that they were saved in a different format :( 

From the code: 
![image](https://user-images.githubusercontent.com/464519/120682593-ede3be80-c49c-11eb-91cd-adec751ed2a3.png)

**Comment by SaraTolstrupHusum** [comment]
I will check asap.

**Comment by eleonora-k** [comment]
<img width="1885" alt="Screen Shot 2021-06-08 at 12 12 24" src="https://user-images.githubusercontent.com/57449991/121168022-cb61f480-c852-11eb-8039-d8fa69b026c1.png">
Sara and I both tried to do exercises and this is what we see. We cannot get to exercises.

**Comment by mircealungu** [comment]
it works for me.
do you have multiple user accounts? does it happen with all of them?
can you look into the console to see maybe which API call fails? 

tak!
m.

**Comment by SaraTolstrupHusum** [comment]
It happened with both our users: sara2, bananas10 and eleonora kurilchik. Now, the problem only persists with bananas10 end eleonora kurilchik. It seems to be the session failing somehow. This is the error in the console.
![image](https://user-images.githubusercontent.com/64850777/121175073-f0f2fc00-c85a-11eb-93fc-6779d363a465.png)

**Comment by SaraTolstrupHusum** [comment]
@mircealungu 
The problem with exercises not loading is still a problem, but the endpoint is working and returning data for students who have done exercises efter we implemented the new logging features.
Can we make the return a list of words instead of an object with the words as properties though? Iterating an object is a lot more complicated than iterating a list.

**Comment by mircealungu** [comment]
Oki. Let's open a new issue for the not-loading exercises. 

And in the meantime I'll give you a list of words instead of a dictionary then.

**Comment by mircealungu** [comment]
@SaraTolstrupHusum: is this what you had in mind? 
![image](https://user-images.githubusercontent.com/464519/121249791-45bb6480-c8a5-11eb-8c2e-da00ce479dcf.png)

**Comment by SaraTolstrupHusum** [comment]
@beamb What are the current possible exercise types, that can be returned as the source?
"MULTIPLE_CHOICE" and "Recognize_L1W_in_L2T"... Anything else?

**Comment by mircealungu** [comment]
Good Question @SaraTolstrupHusum !

Let's decide on a set of names, and once we agree, @beamb updates the exercises and I update the DB to only have a set of names.

As far as I can see we have, till now: 
- Recognize_L1W_in_L2T --> Recognize  (type 1)
- Select_L2W_fitting_L2T --> Triple Choice (type 2)
- Match_three_L1W_to_three_L2W --> Pair Selection (type 3)

**Comment by SaraTolstrupHusum** [comment]
@mircealungu @beamb

If what is after the --> is what we show to the teachers, I suggest:
Recognize_L1W_in_L2T --> Find in text (type 1)
Select_L2W_fitting_L2T --> Pick the word (type 2)
Match_three_L1W_to_three_L2W --> Match 3 pairs (type 3)
(without the "typeX" though)

If we can render whatever we want to the teachers, I am happy with whatever, as long as I know what they are, so I can match on them.

**Comment by mircealungu** [comment]
I like your names better Sara. Go ahead with the mapping :)

**Comment by SaraTolstrupHusum** [comment]
@beamb for backwards compability, I assumed that MULTIPLE_CHOICE is "match 3 pairs" as those were the ones you have showed in meetings and "Match_three_L1W_to_three_L2W" is the only source not currently returned from the DB... Am I correct on that?

**Comment by beamb** [comment]
@SaraTolstrupHusum  MULTIPLE_CHOICE is now "Pick the word" or "Select_L2W_fitting_L2T". The "match 3 pairs" is indeed not yet in the DB and will be "Match_three_L1W_to_three_L2W".
