### ISSUE TITLE
getWordsNeverExercised(studentID, cohortID, duration)

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#73]
should return a list of words that have never been translated but never exercised either because it is excluded by the algorithm or because it has not been scheduled yet

```
//example of return:
[
  {
      word: "something",
      translation: "noget",
      exclusionReason: "Excluded by algorithm"
  },
  {
      word: "else",
      translation: "andet",
      exclusionReason: "Scheduled - not yet practised"
  }
]
```

**Comment by mircealungu** [comment]
https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/6ca43351c0130f570a345cb65959688a55e61f1c/zeeguu_api/api/teacher_dashboard/student_words.py#L20

Can you work with the following output? 

![image](https://user-images.githubusercontent.com/464519/120721408-0f10d300-c4ce-11eb-80d7-371b5493ee81.png)

if `fit_for_study = 1` then you have `Scheduled - not yet practised`. if it is `null` then, that means "Excluded by algorithm".

**Comment by SaraTolstrupHusum** [comment]
Yup. That should work.
