### ISSUE TITLE
getLearnedWords(studentID, cohortID, duration)

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#74]
should return list of all the words that have been categorized as "learned" by the system. (Practised correctly on 4 different/consecutive days.)

```
//example return:
[
    {
      word: "something",
      translation:"noget",
      exerciseAttempts: [
        { date: "Mar 1. 2020", type: "recognise", attempts: "c", feedback:"" },
        { date: "Mar 1. 2020", type: "recognise", attempts: "hc", feedback:"" },
        { date: "Mar 2. 2020", type: "multiple choice", attempts: "c", feedback:"" },
        { date: " Mar 11. 2020", type: "recognise", attempts: "c", feedback:"" },
        { date: "Mar 23. 2020", type: "multiple choice", attempts: "c", feedback:"Too easy" },
      ],
    },
    {
      word: "more",
      translation:"mere",
      exerciseAttempts: [
        { date: "Mar 1. 2020", type: "recognise", attempts: "c", feedback:"" },
        { date: "Mar 1. 2020", type: "recognise", attempts: "hc", feedback:"" },
        { date: "Mar 2. 2020", type: "multiple choice", attempts: "c", feedback:"" },
        { date: " Mar 11. 2020", type: "recognise", attempts: "c", feedback:"" },
        { date: "Mar 23. 2020", type: "multiple choice", attempts: "c", feedback:"Too easy" },
      ],
    },
]
```

**Comment by mircealungu** [comment]
Can you live with this data? 

![image](https://user-images.githubusercontent.com/464519/120723353-decb3380-c4d1-11eb-9591-6815913f3d82.png)

In that case, this is the endpoint for you: 
https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/c7a8da7aab7f142991717025c7b9d1a4be83d24e/zeeguu_api/api/teacher_dashboard/student_words.py#L41

**Comment by SaraTolstrupHusum** [comment]
I should think the data could work. Will try it out later today.

**Comment by SaraTolstrupHusum** [comment]
@mircealungu
I cannot test this as I have no learned words. And it will take me at least four days to get some - providing that the scheduling algorithm schedules the same word for me four days in a row... Can you "cheat" and add some learned words to either my sara2 or my bananas10 user?

**Comment by mircealungu** [comment]
let's see...

**Comment by mircealungu** [comment]
Oh!

The current definition of "learned" includes words that a user reports as "too easy". 

![image](https://user-images.githubusercontent.com/464519/121394573-c46ddb80-c951-11eb-9cd6-b19518da72bd.png)

This means two things:

1. you know how to add words to your "learned words" 
2. we probably need to add a little note as to the "reason" for a word being learned

**Comment by mircealungu** [comment]
So maybe you can make use of something like this? 

![image](https://user-images.githubusercontent.com/464519/121398278-7a86f480-c955-11eb-9e6e-8d1572008df3.png)

I've deployed this new version, and eventually added a learned based on exercises for you!

![image](https://user-images.githubusercontent.com/464519/121399368-a3f45000-c956-11eb-93b5-ed2e4d64b87b.png)

**Comment by SaraTolstrupHusum** [comment]
Lovely. It worked like a charm and is now implemented in the UI as well.
