### ISSUE TITLE
Inconsistency in reading time

### ISSUE THREAD

**Issue by eleonora-k** [zeeguu-ecosystem/Zeeguu-API#75]
We have discovered an inconsistency in reading time presented in the class overview and then in reading activity for a student. For example, in the class overview of DoNotDeleteClass, when selecting activity for 1 year, user sara2 has 10 minutes of reading,  and when summarizing the minutes she spent on reading each article, we get 14 minutes. Do you know what could be causing this? Can it be a rounding issue somewhere?

**Comment by eleonora-k** [comment]
Also, after looking closely at it, I realized that the student object contains correct reading_time and exercises_done, but direct data we get about readingTime and exerciseTIme is not.

**Comment by SaraTolstrupHusum** [comment]
Moved all comments above to already existing issue about the problematic endpoint:
#64 add getStudentActivityOverview endpoint
