### ISSUE TITLE
getCohortName()

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#79]
We need an endpoint for getting the cohort name, when the user is a student and we only have the cohort id.

**Comment by mircealungu** [comment]
https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/2fa31ab6afbca6806bc6690e2863a598614cbc8c/zeeguu_api/api/student.py#L51

returns this:

![image](https://user-images.githubusercontent.com/464519/120723977-1c7c8c00-c4d3-11eb-8bbe-cb1e6b189660.png)

**Comment by SaraTolstrupHusum** [comment]
Works.
