### ISSUE TITLE
Addition of logic expressions to parse_html

### ISSUE THREAD

**Issue by bwesth** [zeeguu-ecosystem/Zeeguu-API#80]
parse_html endpoint should test if the received HTML is actually an article, and send an error response if it is not.
Maybe something like "Viewed page is not an article."

parse_html endpoint should test if the article has already been uploaded by the user, and send an error response if it is.
Maybe something like "This article is already in your Zeeguu texts."

**Comment by mircealungu** [comment]
@bwesth  

> parse_html endpoint should test if the received HTML is actually an article, and send an error response if it is not.
Maybe something like "Viewed page is not an article."

This should not be our problem actually - we do our best to extract text from the page on which the user is. If they are on a page w/o text we'll simply extract no text. 
Also, there is no way for newspaper3k to *know* whether an HTML is an article. Or did you have in mind a specific way of detecting this? 

> parse_html endpoint should test if the article has already been uploaded by the user, and send an error response if it is.
Maybe something like "This article is already in your Zeeguu texts".

What is an article? 
What if there is the same text at two URLs and I want to import it twice? Who is  parse_html to know anything about articles? 
parse_html should do only what its name says it should do: "parse the HTML and give you content". \

There will be an option to delete an article in the My Texts management page in Zeeguu and the user can delete there the articles that they imported twice maybe?
