### ISSUE TITLE
Exercises are not loading for some users

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#81]
<img width="1885" alt="Screen Shot 2021-06-08 at 12 12 24" src="https://user-images.githubusercontent.com/57449991/121168022-cb61f480-c852-11eb-8039-d8fa69b026c1.png">
@mircealungu 
Sara and I both tried to do exercises and this is what we see. We cannot get to exercises.

_Originally posted by @eleonora-k in https://github.com/zeeguu-ecosystem/Zeeguu-API/issues/72#issuecomment-856642775_

**Comment by SaraTolstrupHusum** [comment]
#https://github.com/zeeguu-ecosystem/Zeeguu-API/issues/72#issuecomment-856663755 #

**Comment by SaraTolstrupHusum** [comment]
> It happened with both our users: sara2, bananas10 and eleonora kurilchik. Now, the problem only persists with bananas10 end eleonora kurilchik. It seems to be the session failing somehow. This is the error in the console.
> ![image](https://user-images.githubusercontent.com/64850777/121175073-f0f2fc00-c85a-11eb-93fc-6779d363a465.png)

**Comment by SaraTolstrupHusum** [comment]
@mircealungu Tested with bananas10 and this is still a problem this morning.

**Comment by mircealungu** [comment]
mystery of misteries! why is it calling the session endpiont? 
can you logout and login again?

**Comment by SaraTolstrupHusum** [comment]
I don't know why it is calling the session endpoint... Could it be that it is using the  _appendSessionToUrl api call somewhere???
Anywho... Logging in and out seemed to solve the problem for bananas.
@eleonora-k can you check with your user?

**Comment by SaraTolstrupHusum** [comment]
Could we solve it by implementing some error handling along the lines of: "Your session seems to have expired. Please try to log out and log in again to do more exercises.", I wonder???

**Comment by mircealungu** [comment]
Aaabsolutely we should do!

**Comment by mircealungu** [comment]
does logging out+ in work also for @eleonora-k ?

**Comment by SaraTolstrupHusum** [comment]
@mircealungu The problem is still persisting for Eleonoras user (she also tried in incognito mode).

**Comment by SaraTolstrupHusum** [comment]
We found the reason:
If a student hasn't translated any words the loading spinner never goes away because the current_bookmarks_to_study is null.
We will fix the UI to provide the user with better info.

**Comment by mircealungu** [comment]
nice job finding the bug :)

**Comment by SaraTolstrupHusum** [comment]
Fixed with next pr from newTeacher
