### ISSUE TITLE
inconsistent exercise count

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#82]
@mircealungu
There is a mismatch between the count of exercises in the endpoints: /student_activity_overview and /student_exercise_history.
/student_activity_overview returns a .number_of_exercises that is much higher that the exercise count we get from iterating through the exercise_attempts on the words that we get from /student_exercise_history. The count here is consistent with the number we get from .practiced_words_count in /student_activity_overview

It seems wierd to show that 110 exercises has been completed in a given time period, but that there is then only 28 exerciseattempts shown under practised words.... What do we do?

![image](https://user-images.githubusercontent.com/64850777/121685749-9f4bab00-cac0-11eb-94c8-934d197f1c03.png)

**Comment by mircealungu** [comment]
practiced words: 28
exercises: 110

this simply means that there's the same word that appeared multiple times in exercises.

or?

**Comment by mircealungu** [comment]
Update. My observation remains; but also your observation is also good!

There was a difference between the two endpoints because `student_activity_overview` was counting also exercises before '2021-05-24'.  This is the date when the new exercise types introduced by Beatrice that are not compatible with the previous ones have been introduced. 

I've fixed this by ensuring that both the endpoints only count from that date on.

**Comment by SaraTolstrupHusum** [comment]
@mircealungu
The exercise count is now consistent with the number of exercises that we show under each word, but the number of practised words is not consistent with the number of words returned by `/student_exercise_history`.
Eg: `/student_exercise_history` returns 19 words, but `/student_activity_overview` returns 28 practised words for sara2.

**Comment by mircealungu** [comment]
it is true that the number_of_learned_words also didn't have the cutoff date.
can you test whether now it's ok?
i really don't like this solution with the cutoff date :(

**Comment by SaraTolstrupHusum** [comment]
The number of practiced words is now consistent in both endpoints and the learned words also seems to be ok.
