### ISSUE TITLE
"Old" texts not rendered in new teacher dashboard.

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#84]
If the teachers have added texts in the old dashboard - the texts are not rendering in the new. Why?
(Issue is present in both Pernille and Maries accounts.)
Front or backend issue?

**Comment by mircealungu** [comment]
Backend issue very likely.
I'll look into it tomorrow most likely.

M.

**Comment by mircealungu** [comment]
I fixed the db for Pernille and Marie. 
Can you check with them that their old texts are now visible?

**Comment by SaraTolstrupHusum** [comment]
Checked with Pernille and the old texts are there now.
