### ISSUE TITLE
The list of teachers in the cohorts should not include developers

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/zeeguu-api#87]
https://github.com/zeeguu-ecosystem/zeeguu-api/blob/7915b3e282bd96800f7355033153cce4125a3d13/zeeguu_api/api/teacher_dashboard/cohorts.py#L178

The list of teachers in each cohort returned by this endpoint includes developers. As we are shoving the teachers on the list to the teachers, developers should not be on it.

**Comment by SaraTolstrupHusum** [comment]
@mircealungu
It is really useful as a developer to be able to see the UI with "real" data, so removing us from the real classes is a perfect quick-fix but it is only partly a solution. ;)

**Comment by SaraTolstrupHusum** [comment]
![Skærmbillede 2021-11-22 kl  13 38 20](https://user-images.githubusercontent.com/64850777/142863284-7f52a4a2-83e1-4b3c-863f-93f5f5e376ce.png)

**Comment by mircealungu** [comment]
I fixed it beyond your expectations even :)
now devs don't show up in any real classes; 
problem is that we don't show up in our own created classes; 
I can add us back manually, but let me know to which classes and whom should I add!
